

cc_library(
    name = "muduo_reactor",
    srcs = "reactor/*.cc",
    deps = [
        "//common:muduo_common",
    ],
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test1",
    srcs = "test1.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test2",
    srcs = "test2.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test3",
    srcs = "test3.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test4",
    srcs = "test4.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)


cc_binary(
    name = "test5",
    srcs = "test5.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test6",
    srcs = "test6.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test7",
    srcs = "test7.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)


cc_binary(
    name = "test8",
    srcs = "test8.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test9",
    srcs = "test9.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test10",
    srcs = "test10.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test11",
    srcs = "test11.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)


cc_binary(
    name = "test12",
    srcs = "test12.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

cc_binary(
    name = "test13",
    srcs = "test13.cc",
    deps = ":muduo_reactor",
    optimize = ["-O0", "-g", "-Wall"],
)

